#ifndef NB_CMAKE_CONFIGURE_H
#define NB_CMAKE_CONFIGURE_H

#define NB_CONF_MODULE_NAME "${NB_CONF_MODULE_NAME}"
#define NB_CONF_MODULE_STATIC ${NB_CONF_MODULE_STATIC}
#define NB_CONF_MODULE_SHARED ${NB_CONF_MODULE_SHARED}

#endif
